// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace TasksServices.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.MarkerProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt");

                    b.Property<bool>("Keyboard");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<double>("Opacity");

                    b.Property<int>("RiseOffset");

                    b.Property<bool>("RiseOnHover");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("ZIndexOffset");

                    b.HasKey("Id");

                    b.ToTable("Markers");

                    b.HasData(
                        new { Id = 1, Keyboard = false, Latitude = 46.4768747, Longitude = 22.7541473, Opacity = 0.0, RiseOffset = 0, RiseOnHover = false, Title = "Arieșeni", ZIndexOffset = 0 }
                       
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
